package snotra.awsedukit.awsdynamicservice.model;

import java.nio.ByteBuffer;
import java.time.ZonedDateTime;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "SmellSamples")
public class SmellSample {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	String smell_id;
	
	@DynamoDBAttribute
	ZonedDateTime submissionDate;
	
	@DynamoDBAttribute
	String sumittedSmellType;
	
	@DynamoDBAttribute
	String recognizedSmellType;
	
	@DynamoDBAttribute
	ByteBuffer sampledSmell;
	
	@DynamoDBAttribute
	GeoIP location;
	
	@DynamoDBAttribute
	String submitter;
	
	@DynamoDBAttribute
	Long tempertureInF;
	
	@DynamoDBAttribute
	Long humidity;
	
	@DynamoDBAttribute
	Long matchedProbability;

}
